version: '3'
services:
  spark-master:
    image: ruizhizhong058/spark-master:3.5.1-hadoop3.3.6
    networks:
      - workbench
    deploy:
      replicas: 1
      mode: replicated
      restart_policy:
        condition: on-failure
      labels:
        traefik.docker.network: workbench
        traefik.port: 8080
    env_file:
      - ./hadoop.env

  spark-worker:
    image: ruizhizhong058/spark-worker:3.5.1-hadoop3.3.6
    networks:
      - workbench
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
      labels:
        traefik.docker.network: workbench
        traefik.port: 8081
    env_file:
      - ./hadoop.env

networks:
  workbench:
    external: true
